import '@servicenow/sdk/global'
import type { Table } from '@servicenow/sdk/core'
import type { x_bca_reg_contractor_reg } from './x_bca_reg/data/table/x_bca_reg_contractor_reg.d.now'

// Generated by ServiceNow SDK

declare global {
    namespace Now {
        namespace Internal {
            namespace TableSchemas {
                interface x_bca_reg_contractor_reg extends Helper<typeof x_bca_reg_contractor_reg> {}
            }

            interface Tables {
                x_bca_reg_contractor_reg: Table<TableSchemas.x_bca_reg_contractor_reg, 'task'>
            }
        }
    }
}
